# Generated by Django 3.0.8 on 2020-07-17 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upvotes', models.PositiveIntegerField(default=0, editable=False)),
                ('downvotes', models.PositiveIntegerField(default=0, editable=False)),
                ('points', models.IntegerField(default=0, editable=False)),
                ('num_comments', models.PositiveIntegerField(default=0, editable=False)),
                ('is_ask', models.BooleanField(default=False)),
                ('is_show', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.Item')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('news.item',),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.SmallIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.Item')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('duplicate_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Story')),
            ],
            bases=('news.item',),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at', 'points'], name='news_item_created_f2b812_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at', 'id'], name='news_item_created_10dd57_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['id', 'created_at'], name='news_item_id_b557ce_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.Story'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['domain', 'duplicate_of'], name='news_story_domain_07db78_idx'),
        ),
    ]
