# Generated by Django 3.0.8 on 2020-08-07 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='duplicate_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Story'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at', 'points'], name='news_item_created_f2b812_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at', 'id'], name='news_item_created_10dd57_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['id', 'created_at'], name='news_item_id_b557ce_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.Story'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['domain', 'duplicate_of'], name='news_story_domain_07db78_idx'),
        ),
    ]
